### ISSUE TITLE
라이센스 서버 확인

### ISSUE THREAD

**Issue by sar9702** [mgskorea/tractor#3]
![screenshot from 2018-09-28 11-11-58](https://user-images.githubusercontent.com/14924389/46184258-b695da80-c30f-11e8-80ec-dbd0e222e183.png)

이미 PixarLicense가 설치되어있어 라이센스를 재발급받아 라이센스 파일만 대체하였습니다.

status를 봤을 때 이렇게 나왔는데 잘 실행되고 있는건가요?

**Comment by suyoungP** [comment]
PixarLicense-LA-21.0파일을 status없이 실행해보시고 스크린샷해서 한번 더 보여주세요. :) 
**PixarLicense 파일을 실행했을때 나오는 리스트가 라이선스 파일안에 입력된 것과 같다면 정상적으로 실행되는 것입니다.

**Comment by suyoungP** [comment]
만약 PixarLicense 파일을 실행했는데 리스트가 나오지 않는다면,
./PixarLicense-LA-21.0 -x pixar.license 를 입력해주세요.
/opt/pixar/ 안에 있는 pixar.license를 수동으로 읽을 수 있습니다.

**Comment by sar9702** [comment]
![screenshot from 2018-09-28 14-51-14](https://user-images.githubusercontent.com/14924389/46190454-932e5800-c32e-11e8-9c30-3378e05bae31.png)

라이센스 서버 stop 시키고 ./PixarLicenseServer -x /opt/pixar/pixar.license 을 실행시켰을 때 이렇게 나왔습니다. 10월 25일까지라고 나온거로 봐서 잘 된거 같은데..한 번 확인해주시겠어요??

./PixarLicenseServer -x pixar.license 파일을 찾을 수 없다는 에러가 나와 경로를 다 적어서 실행해봤습니다!!

**Comment by suyoungP** [comment]
서버를 시작시켜야하는데
systemctl start pixar-license.service 를 입력해주세요.
ps -e |grep Pixar 를 입력하여 PixarLicenseServer가 리스트로 나오는지 확인해주세요!
현재 제가 사용 중인건 가장 최신버전인 PixarLicense-LA-22.0버전입니다. 혹시 다를 수 있으니 경과 알려주세용!

**Comment by sar9702** [comment]
![screenshot from 2018-09-28 15-41-54](https://user-images.githubusercontent.com/14924389/46192252-5ade4800-c335-11e8-812a-5a597b2b29a9.png)

/usr/lib/systemd/system에 pixar-license.service 파일이 없어서 systemctl 명령어가 에러가 나네요..

/etc/init.d/pixarlicenseserver start 를 하고 ps -e | grep Pixar를 했을 때 위의 첨부한 사진처럼 리스트가 나와요!!

**Comment by suyoungP** [comment]
pixar license server가 이미 깔려있으시다했는데 설치가 제대로 안되있는 것 같네요!
PixarLicense-LA-21.0폴더 안에있는 linux_installService.sh를 실행시켜주세요.
이 설치를 했음에도 불구하고 service파일이 깔려있지않다면 rpm 자체를 삭제했다가 22.0버전으로 새로 깔아보세요! 
22.0버전은 Pixar RenderMan Forums Download( https://renderman.pixar.com/forum/download.php )에 current releases에서 License Utilities 22.0 (1873521)를 받으시면 됩니당!

**Comment by khw7096** [comment]
존재하지 않는 링크라고 떠서 링크를 조금 수정했어요.
```
Download(https://renderman.pixar.com/forum/download.php)
를..
Download( https://renderman.pixar.com/forum/download.php )
로..
```

**Comment by sar9702** [comment]
트랙터 라이센스와 엔진까지 모두 설치 완료하였습니다!!

**Comment by suyoungP** [comment]
와 축하드립니다!! 껐다 켰는대도 트랙터 엔진이 오류없이 잘 구동되나요?

**Comment by sar9702** [comment]
네 문제 없이 구동됩니다!!ㅎㅎ

**Comment by khw7096** [comment]
문제없이 구동되니 이 이슈는 닫을께요.
